#!/usr/bin/env bash
# Aggregates per-module findings JSONL files into:
#   - audit-report.json (machine-readable, with score + secrets summary)
#   - audit-report.md  (human-readable)
#   - audit-report.html (cyberpunk theme + auto-open) — via lib/html_report.sh
#   - action-plan.md   — via lib/action_plan.sh
#   - secrets-inventory.md is generated by module J as it runs

set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/action_plan.sh"
source "$SCRIPT_DIR/lib/html_report.sh"

OUT_JSON="$AUDIT_DIR/audit-report.json"
OUT_MD="$AUDIT_DIR/audit-report.md"
OUT_HTML="$AUDIT_DIR/audit-report.html"
SECRETS_INVENTORY="$AUDIT_DIR/secrets-inventory.md"
ACTION_PLAN="$AUDIT_DIR/action-plan.md"

# All modules ever produced (alphabetical letters used as IDs).
ALL_MODULES="A B C D E F G H I J K L M N P"

# ---------- Counts by severity ----------
count_sev() {
  local sev="$1"
  grep -hoE '"severity":"'"$sev"'"' "$FINDINGS_DIR"/*.jsonl 2>/dev/null | wc -l | tr -d ' '
}

CRIT=$(count_sev "CRITICAL")
HIGH=$(count_sev "HIGH")
MED=$(count_sev "MEDIUM")
LOW=$(count_sev "LOW")
INFO=$(count_sev "INFO")
TOTAL=$((CRIT + HIGH + MED + LOW + INFO))

# Distinct classified secrets count (rows in inventory minus per-source headers)
SECRETS_DISTINCT=0
if [[ -f "$SECRETS_INVENTORY" ]]; then
  SECRETS_DISTINCT=$(grep -cE '^\| [A-Za-z]' "$SECRETS_INVENTORY" 2>/dev/null) || SECRETS_DISTINCT=0
  SRC_BLOCKS=$(grep -c '^## Source:' "$SECRETS_INVENTORY" 2>/dev/null) || SRC_BLOCKS=0
  SECRETS_DISTINCT=$((SECRETS_DISTINCT - SRC_BLOCKS))
  [[ $SECRETS_DISTINCT -lt 0 ]] && SECRETS_DISTINCT=0
fi

# Security score (algorithm + grade table live in lib/html_report.sh)
SCORE=$(compute_security_score "$CRIT" "$HIGH" "$MED" "$LOW" "$SECRETS_DISTINCT")
GRADE_TSV=$(compute_grade "$SCORE")
GRADE_LETTER="${GRADE_TSV%%$'\t'*}"
GRADE_LABEL="${GRADE_TSV##*$'\t'}"

# Build secrets_inventory_summary as JSON array (per-type aggregation).
# Each entry: { type, service, rotate_url, severity_hint, count, fingerprints[] }
build_secrets_summary_json() {
  [[ -f "$SECRETS_INVENTORY" ]] || { printf '[]'; return; }
  awk -F'|' '
    /^\| Type / { next }
    /^\|[ ]*-/ { next }
    /^\|/ {
      n = split($0, a, /\|/)
      if (n < 6) next
      type=a[2];    gsub(/^ +| +$/, "", type)
      service=a[3]; gsub(/^ +| +$/, "", service)
      rotate=a[4];  gsub(/^ +| +$/, "", rotate)
      sev=a[5];     gsub(/^ +| +$/, "", sev)
      fp=a[6];      gsub(/^ +| +$/, "", fp)
      gsub(/^`|`$/, "", fp)
      if (type == "Type" || type == "") next
      key = type "\t" service "\t" rotate "\t" sev
      counts[key]++
      if (fps[key] == "") fps[key] = fp
      else                fps[key] = fps[key] "\v" fp
    }
    END {
      for (k in counts) printf("%d\t%s\t%s\n", counts[k], k, fps[k])
    }
  ' "$SECRETS_INVENTORY" | sort -k1,1 -nr | awk -F'\t' '
    function jesc(s) {
      # awk gsub: source "\\\\\\\\" → runtime "\\\\" → replacement = 2 literal backslashes
      gsub(/\\/, "\\\\\\\\", s)
      gsub(/"/, "\\\"", s)
      gsub(/\t/, "\\t", s)
      gsub(/\r/, "", s)
      return s
    }
    BEGIN { print "["; first=1 }
    {
      cnt=$1; type=$2; service=$3; rotate=$4; sev=$5; fp_blob=$6
      if (!first) print ","
      first=0
      printf("    {\"type\":\"%s\",\"service\":\"%s\",\"rotate_url\":\"%s\",\"severity_hint\":\"%s\",\"count\":%d,\"fingerprints\":[",
             jesc(type), jesc(service), jesc(rotate), jesc(sev), cnt)
      n = split(fp_blob, fparr, "\v")
      for (i = 1; i <= n; i++) {
        if (i > 1) printf(",")
        printf("\"%s\"", jesc(fparr[i]))
      }
      printf("]}")
    }
    END { print "\n  ]" }
  '
}

# ---------- JSON output ----------
{
  printf '{\n'
  printf '  "generated_at": "%s",\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '  "host_os": "%s",\n' "$OS"
  printf '  "score": %d,\n' "$SCORE"
  printf '  "grade": "%s",\n' "$GRADE_LETTER"
  printf '  "grade_label": "%s",\n' "$GRADE_LABEL"
  printf '  "summary": {\n'
  printf '    "critical": %d,\n' "$CRIT"
  printf '    "high": %d,\n' "$HIGH"
  printf '    "medium": %d,\n' "$MED"
  printf '    "low": %d,\n' "$LOW"
  printf '    "info": %d,\n' "$INFO"
  printf '    "secrets_distinct": %d\n' "$SECRETS_DISTINCT"
  printf '  },\n'
  printf '  "secrets_inventory_summary": '
  build_secrets_summary_json
  printf ',\n'
  printf '  "findings": [\n'
  first=1
  for f in "$FINDINGS_DIR"/*.jsonl; do
    [[ -f "$f" ]] || continue
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      if [[ $first -eq 1 ]]; then
        first=0
      else
        printf ',\n'
      fi
      printf '    %s' "$line"
    done < "$f"
  done
  printf '\n  ]\n}\n'
} > "$OUT_JSON"

# ---------- Markdown report ----------
{
  echo "# AI Agent Audit Report"
  echo
  echo "Generated: $(date)"
  echo
  echo "Host OS: \`$OS\`"
  echo
  echo "## Score"
  echo
  echo "**${SCORE}/100** — Grade **${GRADE_LETTER}** (${GRADE_LABEL})"
  echo
  echo "_Score = 100 − 5×CRITICAL − 1.7×HIGH − 0.3×MEDIUM − 0.05×LOW − (distinct secrets ÷ 20, capped 10), floor 0._"
  echo
  echo "## Summary"
  echo
  echo "| Severity | Count |"
  echo "|----------|------:|"
  echo "| 🔴 CRITICAL | $CRIT |"
  echo "| 🟠 HIGH | $HIGH |"
  echo "| 🟡 MEDIUM | $MED |"
  echo "| 🟢 LOW | $LOW |"
  echo "| ℹ️ INFO | $INFO |"
  echo "| **Total** | **$TOTAL** |"
  if [[ "$SECRETS_DISTINCT" -gt 0 ]]; then
    echo "| 🔑 Distinct classified secrets | $SECRETS_DISTINCT |"
  fi
  echo
  if [[ $CRIT -gt 0 ]]; then
    echo "> ⚠️ **$CRIT critical issue(s) found.** Address these first — they enable documented incident classes."
    echo
  fi

  if [[ -f "$SECRETS_INVENTORY" ]]; then
    echo "> 🔑 **Secrets inventory** at \`$SECRETS_INVENTORY\` — classifies each detected pattern by service, with redacted fingerprints (first 4 + last 4 + length). The audit does not verify whether keys are still active — treat all as live and rotate."
    echo
  fi

  # Render findings by severity
  for sev in CRITICAL HIGH MEDIUM LOW INFO; do
    local_count=$(count_sev "$sev")
    [[ "$local_count" -eq 0 ]] && continue

    case "$sev" in
      CRITICAL) emoji="🔴" ;;
      HIGH)     emoji="🟠" ;;
      MEDIUM)   emoji="🟡" ;;
      LOW)      emoji="🟢" ;;
      INFO)     emoji="ℹ️" ;;
    esac

    echo
    echo "## $emoji $sev findings ($local_count)"
    echo

    for module_letter in $ALL_MODULES; do
      f="$FINDINGS_DIR/$module_letter.jsonl"
      [[ -f "$f" ]] || continue
      while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        printf '%s' "$line" | grep -q '"severity":"'"$sev"'"' || continue

        id=$(json_decode_field "$line" "id")
        title=$(json_decode_field "$line" "title")
        evidence=$(json_decode_field "$line" "evidence")
        remed=$(json_decode_field "$line" "remediation")
        incident=$(json_decode_field "$line" "incident")

        echo "### \`[$module_letter.$id]\` $title"
        echo
        if [[ -n "$evidence" ]]; then
          echo "**Evidence:**"
          echo
          printf '%s\n' "$evidence" | sed 's/^/> /'
          echo
        fi
        if [[ -n "$remed" ]]; then
          echo "**Remediation:**"
          echo
          printf '%s\n' "$remed"
          echo
        fi
        if [[ -n "$incident" ]]; then
          echo "**Related incident:** $incident"
          echo
        fi
      done < "$f"
    done
  done

  echo
  echo "---"
  echo
  echo "## How to interpret severities"
  echo
  echo "- **CRITICAL** — directly enables a documented incident class (Nx s1ngularity-style credential exfil, PocketOS-style production deletion). Fix today."
  echo "- **HIGH** — significantly amplifies blast radius if anything goes wrong. Fix this week."
  echo "- **MEDIUM** — hygiene. Fix this month."
  echo "- **LOW** — best practice."
  echo "- **INFO** — context, no action needed."
  echo
  echo "## Useful commands after audit"
  echo
  echo '```bash'
  echo '# Open the cyberpunk HTML report:'
  echo 'xdg-open ~/.ai-agent-audit/audit-report.html  # Linux'
  echo 'open ~/.ai-agent-audit/audit-report.html      # macOS'
  echo
  echo '# Inspect raw JSONL findings:'
  echo 'cat ~/.ai-agent-audit/findings/A.jsonl | jq'
  echo
  echo '# Count findings by ID across modules:'
  echo 'cat ~/.ai-agent-audit/findings/*.jsonl | jq -r .id | sort | uniq -c'
  echo
  echo '# Get score from JSON:'
  echo 'jq .score ~/.ai-agent-audit/audit-report.json'
  echo '```'
} > "$OUT_MD"

# ---------- Action plan (prioritised checklist) ----------
generate_action_plan

# ---------- HTML report (cyberpunk theme + score) ----------
generate_html_report

log "AGG" "Report written: $OUT_MD"
log "AGG" "JSON written:   $OUT_JSON"
[[ -f "$SECRETS_INVENTORY" ]] && log "AGG" "Secrets inventory: $SECRETS_INVENTORY"
[[ -f "$ACTION_PLAN" ]] && log "AGG" "Action plan: $ACTION_PLAN"
[[ -f "$OUT_HTML" ]] && log "AGG" "HTML report: $OUT_HTML"
log "AGG" "Score: $SCORE/100 [$GRADE_LETTER — $GRADE_LABEL]"
log "AGG" "Findings: CRITICAL=$CRIT HIGH=$HIGH MEDIUM=$MED LOW=$LOW INFO=$INFO  Secrets: $SECRETS_DISTINCT distinct"
